In [27]:
from grove.fermion_transforms.bktransform import BKTransform

In [28]:
n_qubits = 16
bkt = BKTransform(n_qubits)

In [29]:
op = None
for i in range(4):
    if op == None:
        op = bkt.create(i)
    else:
        op *= bkt.create(i)
print op.simplify()

(0.0625+0j)*X0*X2 + (0.0625+0j)*X0*X2*Z3 + -0.0625j*X0*Y2 + -0.0625j*X0*Y2*Z3 + (0.0625+0j)*X0*Z1*X2 + (0.0625+0j)*X0*Z1*X2*Z3 + -0.0625j*X0*Z1*Y2 + -0.0625j*X0*Z1*Y2*Z3 + -0.0625j*Y0*X2 + -0.0625j*Y0*X2*Z3 + (-0.0625-0j)*Y0*Y2 + (-0.0625+0j)*Y0*Y2*Z3 + -0.0625j*Y0*Z1*X2 + -0.0625j*Y0*Z1*X2*Z3 + (-0.0625-0j)*Y0*Z1*Y2 + (-0.0625+0j)*Y0*Z1*Y2*Z3


In [30]:
op = None
for i in range(5):
    if op == None:
        op = bkt.create(i)
    else:
        op *= bkt.create(i)
print op.simplify()

(0.03125+0j)*X0*X2*X4*X5*X7*X15 + -0.03125j*X0*X2*Y4*X5*X7*X15 + (0.03125+0j)*X0*X2*Z3*X4*X5*X7*X15 + -0.03125j*X0*X2*Z3*Y4*X5*X7*X15 + -0.03125j*X0*Y2*X4*X5*X7*X15 + (-0.03125-0j)*X0*Y2*Y4*X5*X7*X15 + -0.03125j*X0*Y2*Z3*X4*X5*X7*X15 + (-0.03125-0j)*X0*Y2*Z3*Y4*X5*X7*X15 + (0.03125+0j)*X0*Z1*X2*X4*X5*X7*X15 + -0.03125j*X0*Z1*X2*Y4*X5*X7*X15 + (0.03125+0j)*X0*Z1*X2*Z3*X4*X5*X7*X15 + -0.03125j*X0*Z1*X2*Z3*Y4*X5*X7*X15 + -0.03125j*X0*Z1*Y2*X4*X5*X7*X15 + (-0.03125-0j)*X0*Z1*Y2*Y4*X5*X7*X15 + -0.03125j*X0*Z1*Y2*Z3*X4*X5*X7*X15 + (-0.03125-0j)*X0*Z1*Y2*Z3*Y4*X5*X7*X15 + -0.03125j*Y0*X2*X4*X5*X7*X15 + (-0.03125-0j)*Y0*X2*Y4*X5*X7*X15 + -0.03125j*Y0*X2*Z3*X4*X5*X7*X15 + (-0.03125-0j)*Y0*X2*Z3*Y4*X5*X7*X15 + (-0.03125+0j)*Y0*Y2*X4*X5*X7*X15 + 0.03125j*Y0*Y2*Y4*X5*X7*X15 + (-0.03125-0j)*Y0*Y2*Z3*X4*X5*X7*X15 + (-0+0.03125j)*Y0*Y2*Z3*Y4*X5*X7*X15 + -0.03125j*Y0*Z1*X2*X4*X5*X7*X15 + (-0.03125-0j)*Y0*Z1*X2*Y4*X5*X7*X15 + -0.03125j*Y0*Z1*X2*Z3*X4*X5*X7*X15 + (-0.03125-0j)*Y0*Z1*X2*Z3*Y4*X5*X7*X15 +

In [54]:
help(op)

Help on PauliSum in module pyquil.paulis object:

class PauliSum(__builtin__.object)
 |  A sum of one or more PauliTerms.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, other)
 |      Adds together this PauliSum with PauliSum, PauliTerm or Number objects. The new term
 |      is then simplified according to the Pauli Algebra rules.
 |      
 |      :param other: a PauliSum, PauliTerm or Number object
 |      :return: A new PauliSum object given by the addition.
 |      :rtype: PauliSum
 |  
 |  __getitem__(self, item)
 |      :param int item: The index of the term in the sum to return
 |      :return: The PauliTerm at the index-th position in the PauliSum
 |      :rtype: PauliTerm
 |  
 |  __init__(self, terms)
 |      :param list terms: A list of PauliTerms.
 |  
 |  __iter__(self)
 |  
 |  __mul__(self, other)
 |      Multiplies together this PauliSum with PauliSum, PauliTerm or Number objects. The new term
 |      is then simplified according to the Pauli Algebra rules.
 |   

In [31]:
op = bkt.create(2) * bkt.create(3)
print op.simplify()

(0.25+0j)*X2 + -0.25j*Y2 + (0.25+0j)*Z1*X2*Z3 + -0.25j*Z1*Y2*Z3


In [32]:
op = bkt.create(2) * bkt.kill(3)
print op.simplify()

(0.25+0j)*X2 + -0.25j*Y2 + (-0.25+0j)*Z1*X2*Z3 + 0.25j*Z1*Y2*Z3


In [38]:
op = bkt.create(3)
print op.simplify()

-0.5j*Y3*X7*X15 + 0.5*Z1*Z2*X3*X7*X15


In [40]:
import numpy as np

In [46]:
n_qubits = 16
bkt = BKTransform(n_qubits)
invariant = np.log2(n_qubits) + 1
for index in range(n_qubits):
    op = bkt.kill(index)
    op_terms = op.terms
    for term in op_terms:
        coeff = term.coefficient
        #  Identify the c Majorana terms by real
        #  coefficients and check their length.
        if not isinstance(coeff, complex):
            print(len(term) == invariant)

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [34]:
for i in op:
    print i

-0.5j*Y3*X7*X15
0.5*Z1*Z2*X3*X7*X15


In [52]:
from referenceqvm.gates import gate_matrix

Z = gate_matrix['Z']

In [53]:
op = bkt.create(3) * bkt.kill(3)
print op

(0.5+0j)*I + (-0.5+0j)*Z1*Z2*Z3


In [68]:
# Bravyi-Kitaev number operator at index 3 matrix
mat = 0.5 * np.eye(2 ** 3) - 0.5 * np.kron(Z, np.kron(Z, Z))
print mat

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]


In [74]:
np.sort(np.linalg.eig(mat)[0])

array([ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.])

In [75]:
np.sort(np.linalg.eigvals(mat))

array([ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.])

In [64]:
from grove.fermion_transforms.jwtransform import JWTransform

jwt = JWTransform()

In [65]:
op = jwt.create(3) * jwt.kill(3)
print op

(0.5+0j)*I + (-0.5+0j)*Z3


In [71]:
# Jordan-Wigner number operator at index 3 matrix
mat = 0.5 * np.eye(2 ** 3) - 0.5 * np.kron(np.eye(2), np.kron(np.eye(2), Z))
print mat

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]


In [73]:
np.sort(np.linalg.eig(mat)[0])

array([ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.])